# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: docker build -t jpetstotre

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: docker build -t jpetstore
      displayName: Build an image
      inputs:
        command: build
        dockerfile: 'tomcat'
        tags: |
          $(tag)